version: "3.9"

services:
  backend1:
    build: ./todo-backend
    container_name: todo-backend1
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./todo-backend:/app
      - ./todo-backend/db.sqlite3:/app/db.sqlite3
    expose:
      - "5000"
    networks:
      - todo-net

  backend2:
    build: ./todo-backend
    container_name: todo-backend2
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - ./todo-backend:/app
      - ./todo-backend/db.sqlite3:/app/db.sqlite3
    expose:
      - "5000"
    networks:
      - todo-net

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
    networks:
      - todo-net

  frontend:
    build: .
    container_name: todo-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://nginx:5000/api
    depends_on:
      - nginx
    networks:
      - todo-net

networks:
  todo-net:
    driver: bridge
