apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
        include       /etc/nginx/mime.types;  
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        server {
            listen 80;
            root /usr/share/nginx/html;
            index index.html;

            # React Router fallback
            location / {
                try_files $uri /index.html;
            }

            # API requests -> backend service
            location /api/ {
                proxy_pass http://backend:5000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
