name: CI/CD - Todo App

on:
  push:
    branches:
      - main

env:
  ACR_NAME: todoappacrs
  AKS_RG: TodoAppRG
  AKS_NAME: TodoAppAKS
  BACKEND_IMAGE: todo-backend
  FRONTEND_IMAGE: todo-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: Get ACR credentials
        id: acr-creds
        run: |
          ACR_USERNAME=$(az acr credential show -n $ACR_NAME --query "username" -o tsv)
          ACR_PASSWORD=$(az acr credential show -n $ACR_NAME --query "passwords[0].value" -o tsv)
          echo "ACR_USERNAME=$ACR_USERNAME" >> $GITHUB_ENV
          echo "ACR_PASSWORD=$ACR_PASSWORD" >> $GITHUB_ENV

      - name: Docker Login to ACR
        uses: docker/login-action@v2
        with:
          username: ${{ env.ACR_USERNAME }}
          password: ${{ env.ACR_PASSWORD }}
          registry: ${{ env.ACR_NAME }}.azurecr.io

      # Backend build
      - name: Build & Push Backend
        run: |
          docker build -t $ACR_NAME.azurecr.io/$BACKEND_IMAGE:latest ./todo-backend
          docker push $ACR_NAME.azurecr.io/$BACKEND_IMAGE:latest

      # Frontend build
      - name: Build & Push Frontend
        run: |
          docker build -t $ACR_NAME.azurecr.io/$FRONTEND_IMAGE:latest .
          docker push $ACR_NAME.azurecr.io/$FRONTEND_IMAGE:latest

      # Get AKS credentials
      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $AKS_RG --name $AKS_NAME --overwrite-existing

      # Deploy backend
      - name: Deploy Backend
        run: |
          kubectl apply -f k8/backend-deployment.yaml
          kubectl apply -f k8/backend-service.yaml
          kubectl set image deployment/backend backend=$ACR_NAME.azurecr.io/$BACKEND_IMAGE:latest

      # Deploy frontend
      - name: Deploy Frontend
        run: |
          kubectl apply -f k8/frontend-nginx-config.yaml
          kubectl apply -f k8/frontend-deployment.yaml
          kubectl apply -f k8/frontend-service.yaml
          kubectl set image deployment/frontend frontend=$ACR_NAME.azurecr.io/$FRONTEND_IMAGE:latest
