name: CI/CD - Todo App

on:
  push:
    branches:
      - main   # or your branch name

env:
  ACR_NAME: todoappacrs          # your ACR name
  AKS_RG: TodoAppRG             # AKS resource group
  AKS_NAME: TodoAppAKS          # AKS cluster name
  BACKEND_IMAGE: todo-backend
  FRONTEND_IMAGE: todo-frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIAL }}

      - name: Azure CLI Setup
        uses: azure/cli@v2
        with:
          inlineScript: |
            az acr login --name $ACR_NAME

      - name: Build & Push Backend
        run: |
          docker build -t $ACR_NAME.azurecr.io/$BACKEND_IMAGE:${{ github.sha }} ./todo-backend
          docker push $ACR_NAME.azurecr.io/$BACKEND_IMAGE:${{ github.sha }}

      - name: Build & Push Frontend
        run: |
          docker build -t $ACR_NAME.azurecr.io/$FRONTEND_IMAGE:${{ github.sha }} ./frontend
          docker push $ACR_NAME.azurecr.io/$FRONTEND_IMAGE:${{ github.sha }}

      - name: Get AKS Credentials
        run: |
          az aks get-credentials --resource-group $AKS_RG --name $AKS_NAME --overwrite-existing

      - name: Deploy to AKS
        run: |
          kubectl set image deployment/backend backend=$ACR_NAME.azurecr.io/$BACKEND_IMAGE:${{ github.sha }}
          kubectl set image deployment/frontend frontend=$ACR_NAME.azurecr.io/$FRONTEND_IMAGE:${{ github.sha }}
